name: youtunee_core
description: Wrap YouTube Music API to get and listening music with no ads.
version: 0.0.2+1
repository: https://github.com/navetacandra/youtunee_core

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  youtube_explode_dart: ^2.3.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
